export enum ORDER_STATUS {
    CREATED = "CREATED",
    PENDING = "PENDING",
    SUCCESS = "SUCCESS",
    FAILED = "FAILED",
    CANCELED = "CANCELED",
    DELETED = "DELETED",
}

export enum TRANSACTION_STATUS {
    CREATED = "CREATED",
    PENDING = "PENDING",
    SUCCESS = "SUCCESS",
    FAILED = "FAILED",
    CANCELED = "CANCELED",
    DELETED = "DELETED",
}

export enum ESIM_STATE {
    NOT_ACTIVE = "NOT_ACTIVE",
    ACTIVE = "ACTIVE",
    EXPIRED = "EXPIRED",
    FINISHED = "FINISHED",
}

export enum STORY_STATUS {
    ENABLED = "ENABLED",
    DISABLED = "DISABLED",
}

export enum NEWSLETTER_STATUS {
    DRAFT = "DRAFT",
    TO_SEND = "TO_SEND",
    DELIVERED = "DELIVERED",
}  
