export enum ORDER_STATUS {
    CREATED = "CREATED",
    PENDING = "PENDING",
    SUCCESS = "SUCCESS",
    FAILED = "FAILED",
    CANCELED = "CANCELED",
    DELETED = "DELETED",
}

export enum ESIM_STATE {
    NOT_ACTIVE = "NOT_ACTIVE",
    ACTIVE = "ACTIVE",
    EXPIRED = "EXPIRED",
    FINISHED = "FINISHED"
}