export const COUNTRIES: any = {
	us: "United States",
	fr: "France",
	cn: "China",
	es: "Spain",
	it: "Italy",
	tr: "Turkey",
	gb: "United Kingdom",
	uk: "United Kingdom",
	de: "Germany",
	mx: "Mexico",
	th: "Thailand",
	hk: "Hong Kong",
	my: "Malaysia",
	gr: "Greece",
	ca: "Canada",
	kr: "South Korea",
	jp: "Japan",
	sg: "Singapore",
	ax: "Åland Islands",
	al: "Albania",
	ad: "Andora",
	ae: "United Arab Emirates",
	ar: "Argentina",
	am: "Armenia",
	au: "Australia",
	at: "Austria",
	az: "Azerbaijan",
	aw: "Aruba",
	ai: "Anguilla",
	be: "Belgium",
	bd: "Bangladesh",
	bg: "Bulgaria",
	bh: "Bahrain",
	ba: "Bosnia and Herzegovina",
	bo: "Bolivia",
	br: "Brazil",
	bn: "Brunei",
	bw: "Botswana",
	cf: "Central African Republic",
	ch: "Switzerland",
	cl: "Chile",
	ci: "Côte dIvoire",
	cd: "Democratic Republic of the Congo",
	cg: "Congo",
	co: "Colombia",
	cr: "Costa Rica",
	cy: "Cyprus",
	cz: "Czech",
	dk: "Denmark",
	dz: "Algeria",
	ec: "Ecuador",
	eg: "Egypt",
	ee: "Estonia",
	fi: "Finland",
	ga: "Gabon",
	ge: "Georgia",
	gg: "Guernsey",
	gh: "Ghana",
	gi: "Gibraltar",
	gw: "Guinea-Bissau",
	hr: "Croatia",
	hu: "Hungary",
	id: "Indonesia",
	im: "Isle of Man",
	in: "India",
	ie: "Ireland",
	ir: "Iran",
	iq: "Iraq",
	is: "Iceland",
	il: "Israel",
	je: "Jersey",
	jo: "Jordan",
	kz: "Kazakhstan",
	kh: "Cambodia",
	ke: "Kenya",
	kg: "Kyrgyzstan",
	kw: "Kuwait",
	la: "Laos",
	lr: "Liberia",
	li: "Liechtenstein",
	lk: "Sri Lanka",
	lt: "Lithuania",
	lu: "Luxembourg",
	lv: "Latvia",
	mo: "Macao",
	ma: "Morocco",
	mc: "Monaco",
	md: "Moldova",
	mg: "Madagascar",
	mk: "North Macedonia",
	ml: "Mali",
	mt: "Malta",
	me: "Montenegro",
	mw: "Malawi",
	ne: "Niger",
	ng: "Nigeria",
	ni: "Nicaragua",
	nl: "Netherlands",
	no: "Norway",
	nz: "New Zealand",
	om: "Oman",
	pk: "Pakistan",
	pa: "Panama",
	pe: "Peru",
	ps: "Palestine",
	ph: "Philippines",
	pl: "Poland",
	pt: "Portugal",
	py: "Paraguay",
	qa: "Qatar",
	re: "Réunion",
	ro: "Romania",
	sa: "Saudi Arabia",
	sn: "Senegal",
	sv: "El Salvador",
	sd: "Sudan",
	rs: "Serbia",
	sk: "Slovakia",
	si: "Slovenia",
	se: "Sweden",
	sz: "Eswatini",
	sc: "Seychelles",
	td: "Chad",
	tn: "Tunisia",
	tw: "Taiwan",
	tz: "Tanzania",
	ug: "Uganda",
	ua: "Ukraine",
	uy: "Uruguay",
	uz: "Uzbekistan",
	vn: "Vietnam",
	za: "South Africa",
	zm: "Zambia",
	xk: "Kosovo",
	"fr-gp": "Guadeloupe",
	bq: "Bonaire, Sint Eustatius, and Saba",
	bs: "Bahamas",
	bb: "Barbados",
	cw: "Curaçao",
	ky: "Cayman Islands",
	dm: "Dominica",
	gp: "Guadeloupe",
	gd: "Grenada",
	gf: "French Guiana",
	ht: "Haiti",
	jm: "Jamaica",
	kn: "Saint Kitts and Nevis",
	lc: "Saint Lucia",
	ms: "Montserrat",
	mq: "Martinique",
	pr: "Puerto Rico",
	tc: "Turks and Caicos Islands",
	tt: "Trinidad and Tobago",
	vc: "Saint Vincent and the Grenadines",
	vg: "British Virgin Islands",
	bf: "Burkina Faso",
	cm: "Cameroon",
	cv: "Cape Verde",
	gm: "The Gambia",
	gn: "Guinea",
	mr: "Mauritania",
	na: "Namibia",
	rw: "Rwanda",
	tg: "Togo",
	bj: "Benin",
	mu: "Mauritius",
	sl: "Sierra Leone",
	ag: "Antigua and Barbuda",
	bz: "Belize",
	gt: "Guatemala",
	hn: "Honduras",
	ve: "Venezuela",
};
