import "./globals.css";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import { Metadata, Viewport } from "next";
import { TelegramProvider, useTelegram } from "@/providers/telegram-provider";
import Script from "next/script";
import ReactQueryProvider from "@/providers/query-provider";
import TonConnectProvider from "@/providers/tonconnect-provider";
import { Toaster } from "@/components/ui/toaster";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    minimumScale: 1,
    userScalable: false,
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReactQueryProvider>
            <TelegramProvider>
                <TonConnectProvider>
                    <html lang="en" suppressHydrationWarning>
                        <body
                            className={cn(
                                "min-h-screen font-sans antialiased overflow-x-hidden bg-background max-w-[460px] no-select",
                                fontSans.variable
                            )}
                        >
                            <Script
                                src="https://telegram.org/js/telegram-web-app.js"
                                strategy="beforeInteractive"
                            />
                            <Script
                                src="https://gateway.sumup.com/gateway/ecom/card/v2/sdk.js"
                            />
                            {children}
                            <Toaster />
                        </body>
                    </html>
                </TonConnectProvider>
            </TelegramProvider>
        </ReactQueryProvider>
    );
}
